source 'https://rubygems.org'


#Core Management
gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'devise'

#Front End Management
gem 'refile'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'simple_form'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem "mini_magick"
gem "refile", require: ["refile/rails", "refile/image_processing"]
gem 'therubyracer', platforms: :ruby

#Testing & Debugging Tools
group :development do 
  gem 'spring'        
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'pry-byebug'
  gem 'thin'
  gem 'annotate'
end