# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3faff3c2979e85715fba118d0438b4b2f42536e1efc871a3919ca78884acfb3a72d088e5bd89774f5883ea56e599beae7610da228a2fbb2d2e8f9252512896f3

test:
  secret_key_base: ac76950f3554a33e6ec3c6eec4eda68b6a7a5bfad107d39457262c0d06e9092446d94fe16352c2465146ec1826aca4525dc4c66fd8231b1ac81ded4bc4c3bd32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
